# Generated by Django 5.2.7 on 2025-12-03 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_patientrecord_patient_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='department',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_code',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['patient_code'], name='records_pat_patient_a5da13_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['full_name'], name='records_pat_full_na_682678_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['attending_physician', '-created_at'], name='records_pat_attendi_e07cae_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(fields=['department', '-created_at'], name='records_pat_departm_97e442_idx'),
        ),
    ]
